spring:
  thymeleaf:
    cache: false
  mvc:
    throw-exception-if-no-handler-found: false
  servlet:
    multipart:
      max-file-size:  100MB
      max-request-size: 10MB
server:
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true

